name: 'Terraform modules lister'
description: |
    Insert in a markdown file the list of Terraform modules found in this repository.
inputs:
  output-file:
    description: File name to insert the modules list.
    required: false
    default: "README.md"
  find-dir:
    description: Relative path to the base directory name where to find modules.
    required: false
    default: "."
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install -r requirements.txt
      shell: bash
    - name: Pass Inputs to Shell
      run: |
          echo "OUTPUT_FILE=${{ inputs.output-file }}" >> $GITHUB_ENV
          echo "FIND_DIR=${{ inputs.find-dir }}" >> $GITHUB_ENV
      shell: bash
    - name: List Terraform modules and insert it
      id: terraform-module-lister
      run: python src/terraform_modules_lister.py
      shell: bash
